"""
Enhanced Mock LLM for realistic offline development and testing.

Provides deterministic, context-aware responses that simulate an LLM's
output for the United Airlines Network Planning agents. Responses are
generated by combining realistic templates with intelligent rule-based 
logic, data analysis, and natural language generation.

Features:
  - Query-aware response generation
  - Context-sensitive insights
  - Data-driven recommendations
  - Realistic business language
  - Multi-turn conversation support
"""

from __future__ import annotations

import time
from typing import Any, Dict, Generator, Optional
import re


class MockLLM:
    """Enhanced deterministic mock language model with context awareness.

    Substitutes for an actual LLM (e.g. Bedrock Claude) during development.
    Produces structured, realistic-sounding responses via intelligent template
    filling, rule-based logic, and context-aware natural language generation.

    Example::

        llm = MockLLM()
        result = llm.generate("route_analysis", {
            "origin": "ORD",
            "destination": "LAX",
            "demand_score": 0.85,
            "revenue_index": 1.32,
            "competition_level": "High",
        })
    """

    # ------------------------------------------------------------------ #
    # Enhanced response templates with natural language
    # ------------------------------------------------------------------ #

    RESPONSE_TEMPLATES: Dict[str, str] = {
        "route_analysis": (
            "📊 **{origin}→{destination} Route Analysis**\n\n"
            "**Current Metrics:**\n"
            "• Demand Score: {demand_score} ({demand_label})\n"
            "• Revenue Index: {revenue_index} ({revenue_class})\n"
            "• Competition Level: {competition_level}\n"
            "• Distance: {distance}nm | Flight time: {flight_hours}h\n"
            "• Current Frequency: {current_freq} weekly flights\n"
            "• Actual Load Factor: {actual_load}%\n"
            "• On-Time Performance: {actual_otp}%\n\n"
            "**Analysis:**\n"
            "{detailed_analysis}\n\n"
            "**Recommendation:**\n"
            "{recommendation}\n\n"
            "**Financial Impact:**\n"
            "Estimated annual revenue impact: ${revenue_impact}M\n"
            "Payback period for capacity increase: {payback_months} months"
        ),
        "disruption_impact": (
            "🚨 **Disruption Impact Assessment**\n\n"
            "**Incident Details:**\n"
            "• Type: {disruption_type}\n"
            "• Severity: {severity} (Risk Level: {risk_level})\n"
            "• Affected Airports: {affected_airports}\n"
            "• Expected Duration: {duration_hours} hours\n"
            "• Estimated Passengers Impacted: {estimated_pax_impact:,}\n\n"
            "**Cascade Impact Analysis:**\n"
            "{cascade_analysis}\n\n"
            "**Mitigation Strategy:**\n"
            "{mitigation_strategy}\n\n"
            "**Recovery Plan:**\n"
            "{recovery_plan}\n\n"
            "**Estimated Recovery Time:** {recovery_hours} hours from disruption end\n"
            "**Estimated Cost:** ${disruption_cost}M"
        ),
        "executive_summary": (
            "📈 **United Airlines Network Operations -- Executive Summary**\n\n"
            "**Fleet & Network Overview:**\n"
            "• Active Aircraft: {total_aircraft} | Utilization: {active_pct}%\n"
            "• Routes Operating: {total_routes} | Daily Flights: {total_flights}\n"
            "• Network Capacity: {total_capacity:,} seats/day\n\n"
            "**Operational Performance:**\n"
            "• On-Time Performance: {otp_pct}% (Target: 82%)\n"
            "• Average Load Factor: {avg_load}% (Target: 85%)\n"
            "• Completion Factor: {completion_pct}%\n"
            "• Active Disruptions: {disruption_count} (Severity: {max_severity})\n\n"
            "**Key Performance Drivers:**\n"
            "{highlights}\n\n"
            "**Strategic Action Items:**\n"
            "{action_items}\n\n"
            "**24-Hour Forecast:**\n"
            "{forecast}"
        ),
        "schedule_gap": (
            "🎯 **Schedule Gap Analysis: {airport}**\n\n"
            "**Analysis Period:** {period}\n"
            "**Identified Gaps:** {gap_count} gaps found\n\n"
            "**Top Revenue Opportunities:**\n"
            "{gap_details}\n\n"
            "**Market Analysis:**\n"
            "• Estimated demand: {estimated_demand:,} pax/month\n"
            "• Competitive response risk: {comp_risk}\n"
            "• Market saturation: {saturation_pct}%\n\n"
            "**Financial Opportunity:**\n"
            "Estimated annual revenue: ${revenue_opportunity}M\n"
            "Net present value (10-year): ${npv}M\n\n"
            "**Implementation Recommendation:**\n"
            "{recommendation}"
        ),
        "anomaly_report": (
            "🔍 **Anomaly Detection Report**\n\n"
            "**Scan Timestamp:** {timestamp}\n"
            "**Total Anomalies Detected:** {anomaly_count}\n"
            "**Severity Distribution:** Critical={critical} | High={high} | Medium={medium} | Low={low}\n\n"
            "**Top Priority Anomalies:**\n"
            "{anomaly_details}\n\n"
            "**System Health Assessment:**\n"
            "{system_health}\n\n"
            "**Root Cause Analysis:**\n"
            "{root_causes}\n\n"
            "**Recommended Actions:**\n"
            "{recommendations}"
        ),
    }

    # ------------------------------------------------------------------ #
    # Enhanced rule functions with business logic
    # ------------------------------------------------------------------ #

    RULES: Dict[str, Any] = {
        # Demand classification
        "demand_label": lambda v: (
            "Very Strong (>0.80)" if v.get("demand_score", 0) >= 0.80
            else "Strong (0.70-0.79)" if v.get("demand_score", 0) >= 0.70
            else "Moderate (0.50-0.69)" if v.get("demand_score", 0) >= 0.50
            else "Weak (<0.50)"
        ),
        "revenue_class": lambda v: (
            "Premium" if v.get("revenue_index", 1.0) >= 1.3
            else "Standard" if v.get("revenue_index", 1.0) >= 0.9
            else "Economy"
        ),
        # Detailed analysis with context
        "detailed_analysis": lambda v: _generate_detailed_analysis(v),
        # Smart recommendation logic
        "recommendation": lambda v: _generate_recommendation(v),
        # Cascade impact analysis
        "cascade_analysis": lambda v: _generate_cascade_analysis(v),
        # Mitigation strategy
        "mitigation_strategy": lambda v: _generate_mitigation_strategy(v),
        # Recovery plan
        "recovery_plan": lambda v: _generate_recovery_plan(v),
        # Financial impact
        "revenue_impact": lambda v: round(
            v.get("revenue_index", 1.0) * v.get("demand_score", 0.5) * 18.5, 1
        ),
        "disruption_cost": lambda v: round(
            v.get("estimated_pax_impact", 1000) * 0.15 * (
                3.0 if v.get("severity") == "Critical"
                else 1.5 if v.get("severity") == "High"
                else 0.5
            ), 2
        ),
        "payback_months": lambda v: max(8, round(
            24 / (v.get("demand_score", 0.5) * v.get("revenue_index", 1.0))
        )),
        "risk_level": lambda v: (
            "🔴 CRITICAL" if v.get("severity") == "Critical"
            else "🟠 HIGH" if v.get("severity") == "High"
            else "🟡 MODERATE" if v.get("severity") == "Medium"
            else "🟢 LOW"
        ),
        # Highlights
        "highlights": lambda v: _generate_highlights(v),
        # Action items
        "action_items": lambda v: _generate_action_items(v),
        # Forecast
        "forecast": lambda v: _generate_forecast(v),
    }

# ============================================================================ #
# Helper functions for realistic response generation
# ============================================================================ #

def _generate_detailed_analysis(v: Dict[str, Any]) -> str:
    """Generate context-aware route analysis narrative."""
    demand = v.get("demand_score", 0)
    revenue_idx = v.get("revenue_index", 1.0)
    competition = v.get("competition_level", "Medium")
    actual_load = v.get("actual_load", 75)
    actual_otp = v.get("actual_otp", 80)
    
    parts = []
    
    # Demand insights
    if demand >= 0.80:
        parts.append(f"This is one of our strongest demand corridors with a demand score of {demand:.2f}.")
        parts.append("Market research indicates consistent business and leisure travel throughout the year.")
    elif demand >= 0.50:
        parts.append(f"Moderate demand profile (score: {demand:.2f}) with seasonal peaks during summer and holidays.")
        parts.append("Revenue opportunity exists through tactical capacity and frequency optimization.")
    else:
        parts.append(f"Lower demand environment (score: {demand:.2f}) requires strategic review.")
        parts.append("Consider seasonal scheduling or partnership opportunities to maintain market presence.")
    
    # Revenue analysis
    if revenue_idx >= 1.3:
        parts.append(f"Premium yield market with revenue index {revenue_idx:.2f}x system average. Business travel dominates.")
    elif revenue_idx >= 0.9:
        parts.append(f"Standard revenue dynamics (index: {revenue_idx:.2f}x) with balanced leisure/business mix.")
    else:
        parts.append(f"Below-average revenue realization (index: {revenue_idx:.2f}x) suggests price sensitivity.")
    
    # Competitive assessment
    if competition == "High":
        parts.append(f"High competitive intensity with 3+ major carriers. Differentiation through schedule or service is critical.")
    elif competition == "Medium":
        parts.append(f"Moderate competition allows for selective capacity growth if demand supports.")
    else:
        parts.append(f"Limited direct competition presents opportunity for market expansion.")
    
    # Performance metrics
    if actual_load >= 85:
        parts.append(f"Strong load factor of {actual_load}% indicates supply-demand balance.")
    elif actual_load >= 75:
        parts.append(f"Acceptable load factor of {actual_load}% with opportunity for yield management.")
    else:
        parts.append(f"Load factor of {actual_load}% suggests potential overc apacity; review frequency.")
    
    if actual_otp >= 85:
        parts.append(f"OTP of {actual_otp}% demonstrates reliable operations from a customer perspective.")
    else:
        parts.append(f"OTP of {actual_otp}% requires operational review to improve schedule integrity.")
    
    return "\n".join(f"• {part}" for part in parts)

def _generate_recommendation(v: Dict[str, Any]) -> str:
    """Generate smart, data-driven recommendations."""
    demand = v.get("demand_score", 0)
    revenue_idx = v.get("revenue_index", 1.0)
    competition = v.get("competition_level", "Medium")
    current_freq = v.get("current_freq", 5)
    
    if demand >= 0.80 and competition != "High":
        return (
            f"✅ **EXPAND CAPACITY**\n"
            f"Increase weekly frequency from {current_freq} to {current_freq + 3} flights.\n"
            f"Deploy larger-gauge aircraft (B787 or B777) on peak days.\n"
            f"Implement premium cabin configuration to capture yield."
        )
    elif demand >= 0.50:
        return (
            f"→ **MAINTAIN & OPTIMIZE**\n"
            f"Keep frequency at {current_freq} weekly flights.\n"
            f"Implement dynamic pricing and yield management.\n"
            f"Monitor competitive entry; prepare expansion response."
        )
    else:
        return (
            f"⚠️ **STRATEGIC REVIEW**\n"
            f"Evaluate seasonal service (peak-only) instead of year-round.\n"
            f"Explore code-share partnerships to maintain presence with lower risk.\n"
            f"Consider redeployment of aircraft to higher-opportunity markets."
        )

def _generate_cascade_analysis(v: Dict[str, Any]) -> str:
    """Generate disruption cascade impact analysis."""
    duration = v.get("duration_hours", 4)
    severity = v.get("severity", "Medium")
    airports = v.get("affected_airports", "N/A")
    pax_impact = v.get("estimated_pax_impact", 5000)
    
    parts = []
    
    if severity == "Critical":
        parts.append(f"**Immediate Impact:** Full hub closure at {airports}. {pax_impact:,} passengers stranded.")
        parts.append(f"**Domino Effect:** {max(10, int(pax_impact/500))} downstream flights disrupted (avg {int(duration*1.5)}h delay).")
        parts.append(f"**Network Stress:** Crew rest violations likely; may trigger additional cancellations.")
        parts.append(f"**Crew Deadhead Cost:** Estimated ${min(50, max(20, int(pax_impact/1000)))}M in crew repositioning.")
    elif severity == "High":
        parts.append(f"**Primary Impact:** {int(pax_impact*0.7):,} passengers delayed, {int(pax_impact*0.2):,} rebooked.")
        parts.append(f"**Secondary Cascade:** {max(5, int(pax_impact/800))} connecting flights at other hubs moderately affected.")
        parts.append(f"**Crew Implications:** Limited rest violations; manageable through duty-time waivers.")
    else:
        parts.append(f"**Localized Impact:** {int(pax_impact*0.4):,} passengers with >30 min delays.")
        parts.append(f"**Network Resilience:** Sufficient schedule slack to absorb impact.")
        parts.append(f"**Operational:** Standard IROPS procedures adequate.")
    
    return "\n".join(f"• {part}" for part in parts)

def _generate_mitigation_strategy(v: Dict[str, Any]) -> str:
    """Generate realistic mitigation actions."""
    severity = v.get("severity", "Medium")
    duration = v.get("duration_hours", 4)
    airports = v.get("affected_airports", "N/A")
    
    if severity == "Critical":
        return (
            "1. **Immediate (0-15 min):** Declare IROPS; activate crisis response team.\n"
            "2. **Communications (0-30 min):** Notify passengers via app/SMS; offer rebooking/hotel.\n"
            "3. **Rebooking (30-60 min):** Prioritize international and connections; offer alternatives.\n"
            "4. **Network Adjustments (60-120 min):** Cancel lower-priority flights to consolidate pax.\n"
            "5. **Crew Management:** Authorize duty-time extensions and premium pay for flexibility.\n"
            "6. **Ground Ops:** Coordinate with airport authority for emergency equipment/gates."
        )
    elif severity == "High":
        return (
            "1. **Alert Status:** Monitor situation; prepare contingency plans.\n"
            "2. **Proactive Rebooking:** Begin for connecting passengers; offer 100-mile upgrades.\n"
            "3. **Schedule Adjustments:** Delay non-critical departures; consolidate if needed.\n"
            "4. **Guest Services:** Deploy additional staff; ensure hotel/meal vouchers available.\n"
            "5. **Crew Notification:** Brief crews on potential duty modifications."
        )
    else:
        return (
            "1. **Monitor:** Track situation; assess trend.\n"
            "2. **Standard Procedures:** Apply normal disruption protocols.\n"
            "3. **Customer Communication:** Proactive notifications every 30 minutes.\n"
            "4. **Operational Flexibility:** Adjust ground handling; prepare alternative gates."
        )

def _generate_recovery_plan(v: Dict[str, Any]) -> str:
    """Generate recovery strategy."""
    duration = v.get("duration_hours", 4)
    recovery_hrs = v.get("recovery_hours", round(duration * 1.5, 1))
    
    return (
        f"1. **Pre-Recovery (Last 30 min of disruption):** Issue push notifications; prepare gates.\n"
        f"2. **Phase 1 (First 1-2h post-disruption):** Resume operations at 50% capacity.\n"
        f"3. **Phase 2 (2-4h post):** Increase to 80% capacity; prioritize connecting pax.\n"
        f"4. **Phase 3 (4+h post):** Return to normal operations.\n"
        f"5. **Post-Incident:** Full recovery target: {recovery_hrs} hours. Follow-up: Publish incident report."
    )

def _generate_highlights(v: Dict[str, Any]) -> str:
    """Generate operational highlights."""
    otp = v.get("otp_pct", 82)
    load = v.get("avg_load", 83)
    disruptions = v.get("disruption_count", 0)
    
    highlights = []
    if otp >= 82:
        highlights.append(f"• ✅ OTP target achieved at {otp}% (strong operational execution)")
    else:
        highlights.append(f"• ⚠️ OTP at {otp}% (below 82% target; investigate causes)")
    
    if load >= 85:
        highlights.append(f"• ✅ Load factor {load}% signals strong pricing power")
    elif load >= 75:
        highlights.append(f"• → Load factor {load}% approaching target")
    else:
        highlights.append(f"• ⚠️ Load factor {load}% suggests overcapacity")
    
    if disruptions == 0:
        highlights.append("• ✅ Zero active disruptions; network healthy")
    else:
        highlights.append(f"• ⚠️ {disruptions} active disruption(s); monitor for cascades")
    
    return "\n".join(highlights)

def _generate_action_items(v: Dict[str, Any]) -> str:
    """Generate prioritized action items."""
    otp = v.get("otp_pct", 82)
    load = v.get("avg_load", 83)
    
    items = []
    items.append("1. **24-Hour Forecast:** Review weather impacts; pre-position crews as needed")
    
    if otp < 82:
        items.append("2. **Operational Focus:** Investigate chronic delay sources; implement countermeasures")
    if load < 75:
        items.append("3. **Capacity Review:** Analyze underutilized flights; consider consolidation")
    
    items.append("4. **Route Optimization:** Evaluate network pricing during peak periods")
    items.append("5. **Crew Scheduling:** Ensure adequate rest buffer for unexpected extensions")
    
    return "\n".join(items)

def _generate_forecast(v: Dict[str, Any]) -> str:
    """Generate 24-hour forecast."""
    return (
        "**Weather:** IFR conditions expected at ORD/DEN; expect 15-30 min delays during peak hours.\n"
        "**Demand:** Slightly elevated for eastbound flights (business travel uptick).\n"
        "**Capacity:** Forecast utilization 88%; high but manageable.\n"
        "**Risk:** Low weather risk turning moderate if storms intensify; monitoring active."
    )


    # ------------------------------------------------------------------ #
    # Public methods
    # ------------------------------------------------------------------ #

    def generate(
        self,
        template_key: str,
        variables: Dict[str, Any],
    ) -> str:
        """Generate a contextual response by filling a template with rules and variables.

        Args:
            template_key: Key into ``RESPONSE_TEMPLATES``.
            variables: Dict of values to inject into the template.

        Returns:
            The rendered response string with realistic insights.

        Raises:
            KeyError: If the template_key does not exist.
        """
        if template_key not in self.RESPONSE_TEMPLATES:
            raise KeyError(
                f"Unknown template key '{template_key}'. "
                f"Available: {list(self.RESPONSE_TEMPLATES.keys())}"
            )

        # Evaluate all rules and merge with supplied variables
        enriched: Dict[str, Any] = dict(variables)
        for rule_name, rule_fn in self.RULES.items():
            if rule_name not in enriched:
                try:
                    enriched[rule_name] = rule_fn(variables)
                except Exception as e:
                    enriched[rule_name] = "N/A"

        template = self.RESPONSE_TEMPLATES[template_key]
        try:
            response = template.format(**enriched)
            return response
        except KeyError as exc:
            return (
                f"[MockLLM] Template rendering incomplete -- missing "
                f"variable {exc}. Supplied keys: {list(enriched.keys())}"
            )

    def generate_from_query(
        self,
        query: str,
        context: Dict[str, Any],
    ) -> str:
        """Generate a response directly from a user query with context.
        
        This method infers the appropriate template and enriches context
        based on the query content.
        
        Args:
            query: Natural language user query.
            context: Contextual data from the system.
        
        Returns:
            A contextual response string.
        """
        intent = self.classify_intent(query)
        
        # Enrich context with query-specific insights
        enriched = dict(context)
        enriched["query"] = query
        enriched["generated_at"] = "realtime"
        
        # Extract specific entities from query for targeted responses
        if "vs" in query.lower() or "compare" in query.lower():
            enriched["comparison_mode"] = True
        if "forecast" in query.lower() or "predict" in query.lower():
            enriched["include_forecast"] = True
        if "why" in query.lower() or "reason" in query.lower():
            enriched["explain_reasoning"] = True
            
        return self.generate(intent, enriched)

    def classify_intent(self, query: str) -> str:
        """Intelligently classify a natural-language query into a system intent.

        Uses keyword matching with scoring to determine the most likely intent.
        Falls back to executive_summary for ambiguous queries.

        Args:
            query: User query string (case-insensitive).

        Returns:
            Intent string: ``route_analysis``, ``disruption_impact``,
            ``executive_summary``, ``schedule_gap``, or ``anomaly_report``.
        """
        query_lower = query.lower()

        intent_keywords: Dict[str, list[str]] = {
            "route_analysis": [
                "route", "demand", "frequency", "city pair", "market",
                "competition", "revenue", "network", "hub", "analyze route",
                "which route", "performance", "capacity",
            ],
            "disruption_impact": [
                "disruption", "weather", "storm", "delay", "cancel",
                "grounding", "irops", "irregular", "divert", "gate closure",
                "mechanical", "impact", "what if", "scenario", "cascade",
            ],
            "executive_summary": [
                "summary", "executive", "overview", "dashboard", "status",
                "kpi", "performance", "report", "how many", "show me",
            ],
            "schedule_gap": [
                "schedule", "gap", "opportunity", "underserved", "slot",
                "timing", "connection", "when", "expand to", "new route",
            ],
            "anomaly_report": [
                "anomaly", "anomalies", "unusual", "outlier", "spike",
                "abnormal", "alert", "warning", "wrong", "issue",
            ],
        }

        scores: Dict[str, int] = {}
        for intent, keywords in intent_keywords.items():
            scores[intent] = sum(1 for kw in keywords if kw in query_lower)

        best_intent = max(scores, key=scores.get)  # type: ignore[arg-type]
        if scores[best_intent] == 0:
            return "executive_summary"  # default fallback
        return best_intent

    def stream_response(
        self, text: str, delay: float = 0.03
    ) -> Generator[str, None, None]:
        """Yield words from *text* one at a time with a small delay.

        Simulates the streaming behaviour of a real LLM API for responsive UX.

        Args:
            text: The full response text to stream.
            delay: Seconds to wait between words (for realistic feel).

        Yields:
            One word (plus trailing space) at a time.
        """
        words = text.split()
        for i, word in enumerate(words):
            suffix = " " if i < len(words) - 1 else ""
            yield word + suffix
            time.sleep(delay)
