"""
Mock LLM for offline development and testing.

Provides deterministic, template-driven responses that simulate an LLM's
output for the United Airlines Network Planning agents.  Responses are
generated by combining pre-defined templates with rule-based logic applied
to caller-supplied variables.
"""

from __future__ import annotations

import time
from typing import Any, Dict, Generator, Optional


class MockLLM:
    """Deterministic mock language model.

    Substitutes for an actual LLM (e.g. Bedrock Claude) during development.
    Produces structured, realistic-sounding responses via template filling
    and simple rule evaluation.

    Example::

        llm = MockLLM()
        result = llm.generate("route_analysis", {
            "origin": "ORD",
            "destination": "LAX",
            "demand_score": 0.85,
            "revenue_index": 1.32,
            "competition_level": "High",
        })
    """

    # ------------------------------------------------------------------ #
    # Response templates
    # ------------------------------------------------------------------ #

    RESPONSE_TEMPLATES: Dict[str, str] = {
        "route_analysis": (
            "Route Analysis: {origin} -> {destination}\n"
            "-------------------------------------------\n"
            "Demand Score : {demand_score} ({demand_label})\n"
            "Revenue Index: {revenue_index}\n"
            "Competition  : {competition_level}\n\n"
            "Recommendation: {action}\n\n"
            "Rationale: The {origin}-{destination} route shows {demand_label} "
            "demand with a revenue index of {revenue_index}. Given the "
            "{competition_level} competitive environment, the recommended "
            "action is to {action_detail}. Estimated annual revenue impact: "
            "${revenue_impact}M."
        ),
        "disruption_impact": (
            "Disruption Impact Assessment\n"
            "============================\n"
            "Type     : {disruption_type}\n"
            "Severity : {severity}\n"
            "Airports : {affected_airports}\n"
            "Duration : {duration_hours} hours\n"
            "Pax Impact: {estimated_pax_impact:,} passengers\n\n"
            "Risk Level: {risk_level}\n\n"
            "Immediate Actions Required:\n"
            "1. Activate IROPS (Irregular Operations) protocol.\n"
            "2. Notify affected passengers via push notification.\n"
            "3. {mitigation_action}\n"
            "4. Coordinate with crew scheduling for repositioning.\n\n"
            "Estimated recovery time: {recovery_hours} hours from disruption "
            "end."
        ),
        "executive_summary": (
            "United Airlines Network Operations -- Executive Summary\n"
            "======================================================\n\n"
            "Fleet Status: {total_aircraft} aircraft | {active_pct}% active\n"
            "Network: {total_routes} routes | {total_flights} flights today\n"
            "On-Time Performance: {otp_pct}%\n"
            "Average Load Factor: {avg_load}%\n"
            "Active Disruptions: {disruption_count}\n\n"
            "Key Highlights:\n"
            "- {highlight_1}\n"
            "- {highlight_2}\n"
            "- {highlight_3}\n\n"
            "Action Items: {action_items}"
        ),
        "schedule_gap": (
            "Schedule Gap Analysis: {airport}\n"
            "-----------------------------------\n"
            "Analysis Period: {period}\n"
            "Identified Gaps: {gap_count}\n\n"
            "Top Gaps:\n{gap_details}\n\n"
            "Revenue Opportunity: ${revenue_opportunity}M annually\n"
            "Recommendation: {recommendation}"
        ),
        "anomaly_report": (
            "Anomaly Detection Report\n"
            "========================\n"
            "Scan Timestamp: {timestamp}\n"
            "Anomalies Detected: {anomaly_count}\n"
            "Severity Breakdown: Critical={critical}, High={high}, "
            "Medium={medium}, Low={low}\n\n"
            "Top Anomalies:\n{anomaly_details}\n\n"
            "System Health: {system_health}\n"
            "Recommended Actions: {recommendations}"
        ),
    }

    # ------------------------------------------------------------------ #
    # Rule functions
    # ------------------------------------------------------------------ #

    RULES: Dict[str, Any] = {
        "demand_label": lambda v: (
            "Strong" if v.get("demand_score", 0) >= 0.7
            else "Moderate" if v.get("demand_score", 0) >= 0.4
            else "Weak"
        ),
        "action": lambda v: (
            "Increase frequency"
            if v.get("demand_score", 0) >= 0.7 and v.get("competition_level") != "High"
            else "Maintain current frequency"
            if v.get("demand_score", 0) >= 0.4
            else "Evaluate for reduction or seasonal service"
        ),
        "action_detail": lambda v: (
            "increase weekly frequency by 20-30% and deploy larger-gauge "
            "aircraft on peak days"
            if v.get("demand_score", 0) >= 0.7 and v.get("competition_level") != "High"
            else "maintain the current schedule while monitoring competitive "
            "dynamics and seasonal demand shifts"
            if v.get("demand_score", 0) >= 0.4
            else "reduce to seasonal-only service or replace with code-share "
            "partnership to preserve market presence"
        ),
        "revenue_impact": lambda v: round(
            v.get("revenue_index", 1.0) * v.get("demand_score", 0.5) * 18.5, 1
        ),
        "risk_level": lambda v: (
            "CRITICAL" if v.get("severity") == "Critical"
            else "HIGH" if v.get("severity") == "High"
            else "MODERATE" if v.get("severity") == "Medium"
            else "LOW"
        ),
        "mitigation_action": lambda v: (
            "Initiate full ground stop and open rebooking channels for all "
            "affected flights."
            if v.get("severity") == "Critical"
            else "Begin proactive rebooking for connecting passengers."
            if v.get("severity") == "High"
            else "Monitor situation and prepare contingency plans."
        ),
        "recovery_hours": lambda v: round(
            v.get("duration_hours", 4) * 1.5, 1
        ),
    }

    # ------------------------------------------------------------------ #
    # Public methods
    # ------------------------------------------------------------------ #

    def generate(
        self,
        template_key: str,
        variables: Dict[str, Any],
    ) -> str:
        """Generate a response by filling a template with rules and variables.

        Args:
            template_key: Key into ``RESPONSE_TEMPLATES``.
            variables: Dict of values to inject into the template.

        Returns:
            The rendered response string.

        Raises:
            KeyError: If the template_key does not exist.
        """
        if template_key not in self.RESPONSE_TEMPLATES:
            raise KeyError(
                f"Unknown template key '{template_key}'. "
                f"Available: {list(self.RESPONSE_TEMPLATES.keys())}"
            )

        # Evaluate all rules and merge with supplied variables
        enriched: Dict[str, Any] = dict(variables)
        for rule_name, rule_fn in self.RULES.items():
            if rule_name not in enriched:
                try:
                    enriched[rule_name] = rule_fn(variables)
                except Exception:
                    enriched[rule_name] = "N/A"

        template = self.RESPONSE_TEMPLATES[template_key]
        try:
            return template.format(**enriched)
        except KeyError as exc:
            return (
                f"[MockLLM] Template rendering incomplete -- missing "
                f"variable {exc}. Supplied keys: {list(enriched.keys())}"
            )

    def classify_intent(self, query: str) -> str:
        """Classify a natural-language query into a system intent.

        Uses simple keyword matching to determine the most likely intent.

        Args:
            query: User query string.

        Returns:
            Intent string such as ``route_analysis``, ``disruption_impact``,
            ``executive_summary``, ``schedule_gap``, or ``anomaly_report``.
        """
        query_lower = query.lower()

        intent_keywords: Dict[str, list[str]] = {
            "route_analysis": [
                "route", "demand", "frequency", "city pair", "market",
                "competition", "revenue", "network", "hub",
            ],
            "disruption_impact": [
                "disruption", "weather", "storm", "delay", "cancel",
                "grounding", "irops", "irregular", "divert", "gate closure",
                "mechanical",
            ],
            "executive_summary": [
                "summary", "executive", "overview", "dashboard", "status",
                "kpi", "performance", "report",
            ],
            "schedule_gap": [
                "schedule", "gap", "opportunity", "underserved", "slot",
                "timing", "connection",
            ],
            "anomaly_report": [
                "anomaly", "anomalies", "unusual", "outlier", "spike",
                "abnormal", "alert", "warning",
            ],
        }

        scores: Dict[str, int] = {}
        for intent, keywords in intent_keywords.items():
            scores[intent] = sum(1 for kw in keywords if kw in query_lower)

        best_intent = max(scores, key=scores.get)  # type: ignore[arg-type]
        if scores[best_intent] == 0:
            return "executive_summary"  # default fallback
        return best_intent

    def stream_response(
        self, text: str, delay: float = 0.03
    ) -> Generator[str, None, None]:
        """Yield words from *text* one at a time with a small delay.

        Simulates the streaming behaviour of a real LLM API.

        Args:
            text: The full response text to stream.
            delay: Seconds to wait between words.

        Yields:
            One word (plus trailing space) at a time.
        """
        words = text.split()
        for i, word in enumerate(words):
            suffix = " " if i < len(words) - 1 else ""
            yield word + suffix
            time.sleep(delay)
